name: fied2
channels:
  - pkgs/main
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main/
dependencies:
  - arrow-cpp=9.0.0=py39h93fcf85_10_cpu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=pyh71513ae_1
  - aws-c-cal=0.5.11=he19cf47_0
  - aws-c-common=0.6.2=h8ffe710_0
  - aws-c-event-stream=0.2.7=h70e1b0c_13
  - aws-c-io=0.10.5=h2fe331c_0
  - aws-checksums=0.1.11=h1e232aa_7
  - aws-sdk-cpp=1.8.186=h93d3aa3_4
  - backcall=0.2.0=pyhd3eb1b0_0
  - blosc=1.21.1=h74325e0_3
  - boost-cpp=1.78.0=h9f4b32c_1
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - brotlipy=0.7.0=py39ha55989b_1005
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.18.1=h8ffe710_0
  - ca-certificates=2023.12.12=haa95532_0
  - cairo=1.16.0=hd694305_1014
  - certifi=2023.11.17=py39haa95532_0
  - cffi=1.15.1=py39h68f70e3_2
  - cfitsio=4.1.0=h5a969a9_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=win_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.6=py39h1f6ef14_0
  - cryptography=38.0.3=py39h58e9bdb_0
  - curl=7.86.0=heaf79c2_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py39haa95532_0
  - exceptiongroup=1.0.4=py39haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h1537add_0
  - fiona=1.8.22=py39h9e0966e_2
  - folium=0.13.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py39ha55989b_1
  - freetype=2.12.1=h546665d_0
  - freexl=1.0.6=h67ca5e6_1
  - gdal=3.5.3=py39h34c8707_2
  - geopandas=0.12.1=pyhd8ed1ab_1
  - geopandas-base=0.12.1=pyha770c72_1
  - geos=3.11.1=h1537add_0
  - geotiff=1.7.1=h4ffd875_4
  - gettext=0.21.1=h5728263_0
  - gflags=2.2.2=ha925a31_1004
  - glib=2.74.1=h12be248_1
  - glib-tools=2.74.1=h12be248_1
  - glog=0.6.0=h4797de2_0
  - gst-plugins-base=1.21.1=h001b923_1
  - gstreamer=1.21.1=h6b5321d_1
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.12.2=nompi_h2a0e4a3_100
  - icu=70.1=h0e60522_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h57928b3_3787
  - ipython=8.15.0=py39haa95532_0
  - jedi=0.18.1=py39haa95532_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_2
  - kealib=1.4.15=hdf81f3a_1
  - kiwisolver=1.4.4=py39h1f6ef14_1
  - krb5=1.19.3=h1176d77_0
  - lcms2=2.14=h90d422f_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20220623.0=cxx17_h1a56200_5
  - libblas=3.9.0=16_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=16_win64_mkl
  - libclang=15.0.5=default_h77d9078_0
  - libclang13=15.0.5=default_h77d9078_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=7.86.0=heaf79c2_1
  - libdeflate=1.14=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libgdal=3.5.3=h6176ca1_2
  - libglib=2.74.1=he8f3873_1
  - libgoogle-cloud=2.3.0=h1478941_1
  - libgrpc=1.49.1=h535cfc9_1
  - libiconv=1.17=h8ffe710_0
  - libkml=1.3.0=hf2ab4e4_1015
  - liblapack=3.9.0=16_win64_mkl
  - libnetcdf=4.8.1=nompi_h8c042bf_106
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.38=h19919ed_0
  - libpq=14.5=h04fd8be_1
  - libprotobuf=3.21.9=h12be248_0
  - librttopo=1.1.0=he22b5cd_12
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.0.1=h07bf483_22
  - libsqlite=3.40.0=hcfcfb64_0
  - libssh2=1.10.0=h680486a_3
  - libthrift=0.16.0=h9f558f2_2
  - libtiff=4.4.0=h8e97e67_4
  - libutf8proc=2.8.0=h82a8f57_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.2.4=h8ffe710_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.3=hc3477c8_0
  - libzip=1.9.2=hfed4ece_1
  - libzlib=1.2.13=hcfcfb64_4
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39ha55989b_2
  - matplotlib=3.6.2=py39hcbf5309_0
  - matplotlib-base=3.6.2=py39haf65ace_0
  - matplotlib-inline=0.1.6=py39haa95532_0
  - mkl=2022.1.0=h6a75c08_874
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - networkx=2.8.8=pyhd8ed1ab_0
  - numpy=1.23.4=py39hbccbffa_1
  - openjpeg=2.5.0=hc9384bd_1
  - openpyxl=3.0.10=py39h2bbff1b_0
  - openssl=1.1.1w=h2bbff1b_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.2.0=py39h2e25243_1
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre=8.45=h0e60522_0
  - pcre2=10.40=h17e33f8_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py39h595c93f_3
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - plotly=5.11.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - poppler=22.11.0=ha6c1112_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.5=h392df6f_1
  - proj=9.1.0=h3863b3b_0
  - prompt-toolkit=3.0.36=py39haa95532_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=9.0.0=py39h2c50fde_10_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=py39haa95532_1
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.4.0=py39h9727d73_2
  - pyqt=5.15.7=py39hb77abff_2
  - pyqt5-sip=12.11.0=py39h99910a6_2
  - pysocks=1.7.1=pyh0701188_6
  - python=3.9.18=h6244533_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.6=pyhd8ed1ab_0
  - pyxlsb=1.0.10=pyhd8ed1ab_0
  - pyyaml=6.0=py39ha55989b_5
  - qt-main=5.15.6=h9c3277a_1
  - re2=2022.06.01=h0e60522_0
  - requests=2.28.1=pyhd8ed1ab_1
  - rtree=1.0.1=py39h09fdee3_1
  - scikit-learn=1.1.3=py39h6fe01c0_1
  - scipy=1.9.3=py39hfbf2dce_2
  - seaborn=0.12.1=hd8ed1ab_0
  - seaborn-base=0.12.1=pyhd8ed1ab_0
  - setuptools=59.8.0=py39hcbf5309_1
  - shapely=1.8.5=py39h7c5f289_2
  - sip=6.7.4=py39h99910a6_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hfb803bf_2
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.5=py39hc266a54_2
  - tbb=2021.7.0=h91493d7_0
  - tenacity=8.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.11.3=h5689973_1
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.2=py39ha55989b_1
  - traitlets=5.7.1=py39haa95532_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022f=h191b570_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.0.0=py39ha55989b_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - vc=14.3=h3d8a991_9
  - vs2015_runtime=14.32.31332=h1d6e394_9
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xerces-c=3.2.4=h63175ca_1
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2022.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zlib=1.2.13=hcfcfb64_4
  - zstd=1.5.2=h7755175_4
  - pip:
    - kaleido==0.2.1
prefix: C:\Users\cmcmilla\AppData\Local\Continuum\anaconda3\envs\fied2
